// Generated by gencpp from file sniper_cam/interopImages.msg
// DO NOT EDIT!


#ifndef SNIPER_CAM_MESSAGE_INTEROPIMAGES_H
#define SNIPER_CAM_MESSAGE_INTEROPIMAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sniper_cam
{
template <class ContainerAllocator>
struct interopImages_
{
  typedef interopImages_<ContainerAllocator> Type;

  interopImages_()
    : gps_lat(0.0)  {
    }
  interopImages_(const ContainerAllocator& _alloc)
    : gps_lat(0.0)  {
  (void)_alloc;
    }



   typedef float _gps_lat_type;
  _gps_lat_type gps_lat;




  typedef boost::shared_ptr< ::sniper_cam::interopImages_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sniper_cam::interopImages_<ContainerAllocator> const> ConstPtr;

}; // struct interopImages_

typedef ::sniper_cam::interopImages_<std::allocator<void> > interopImages;

typedef boost::shared_ptr< ::sniper_cam::interopImages > interopImagesPtr;
typedef boost::shared_ptr< ::sniper_cam::interopImages const> interopImagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sniper_cam::interopImages_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sniper_cam::interopImages_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sniper_cam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sniper_cam': ['/home/garrett/vision/vision_ws/src/sniper_cam/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sniper_cam::interopImages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sniper_cam::interopImages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sniper_cam::interopImages_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sniper_cam::interopImages_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sniper_cam::interopImages_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sniper_cam::interopImages_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sniper_cam::interopImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be350a6f6b980def99e12724f4fb21de";
  }

  static const char* value(const ::sniper_cam::interopImages_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe350a6f6b980defULL;
  static const uint64_t static_value2 = 0x99e12724f4fb21deULL;
};

template<class ContainerAllocator>
struct DataType< ::sniper_cam::interopImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sniper_cam/interopImages";
  }

  static const char* value(const ::sniper_cam::interopImages_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sniper_cam::interopImages_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 gps_lat\n\
";
  }

  static const char* value(const ::sniper_cam::interopImages_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sniper_cam::interopImages_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gps_lat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interopImages_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sniper_cam::interopImages_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sniper_cam::interopImages_<ContainerAllocator>& v)
  {
    s << indent << "gps_lat: ";
    Printer<float>::stream(s, indent + "  ", v.gps_lat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNIPER_CAM_MESSAGE_INTEROPIMAGES_H
