// Generated by gencpp from file click_to_geolocate/IntList.msg
// DO NOT EDIT!


#ifndef CLICK_TO_GEOLOCATE_MESSAGE_INTLIST_H
#define CLICK_TO_GEOLOCATE_MESSAGE_INTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace click_to_geolocate
{
template <class ContainerAllocator>
struct IntList_
{
  typedef IntList_<ContainerAllocator> Type;

  IntList_()
    : data()  {
    }
  IntList_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::click_to_geolocate::IntList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::click_to_geolocate::IntList_<ContainerAllocator> const> ConstPtr;

}; // struct IntList_

typedef ::click_to_geolocate::IntList_<std::allocator<void> > IntList;

typedef boost::shared_ptr< ::click_to_geolocate::IntList > IntListPtr;
typedef boost::shared_ptr< ::click_to_geolocate::IntList const> IntListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::click_to_geolocate::IntList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::click_to_geolocate::IntList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace click_to_geolocate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'click_to_geolocate': ['/home/garrett/vision/vision_ws/src/click_to_geolocate/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::click_to_geolocate::IntList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::click_to_geolocate::IntList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::click_to_geolocate::IntList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::click_to_geolocate::IntList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::click_to_geolocate::IntList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::click_to_geolocate::IntList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::click_to_geolocate::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "563b27884d008b0d2adff54dc1f9e4f5";
  }

  static const char* value(const ::click_to_geolocate::IntList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x563b27884d008b0dULL;
  static const uint64_t static_value2 = 0x2adff54dc1f9e4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::click_to_geolocate::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "click_to_geolocate/IntList";
  }

  static const char* value(const ::click_to_geolocate::IntList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::click_to_geolocate::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] data\n\
";
  }

  static const char* value(const ::click_to_geolocate::IntList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::click_to_geolocate::IntList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::click_to_geolocate::IntList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::click_to_geolocate::IntList_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLICK_TO_GEOLOCATE_MESSAGE_INTLIST_H
